### ISSUE TITLE
Auth doesn't work consistently

### ISSUE THREAD

**Issue by thomaswilburn** [akoh0001/chat#1]
I started looking into your auth issue tonight. Unfortunately, I can't completely test locally because I don't have your user database (and also it seems like you may be missing some files, because the server kept crashing). But I have an idea, based on looking at your code and comparing it to the example and the npmjs.com site.

What I noticed is that when NPM registers the cookie auth strategy, they specify "required" as the mode, meaning that by default routes are locked to auth. On the public routes, they use a mixin to loosen that restriction and convert them to the "try" mode.

On your site, however, you're registering the strategy without a mode, which means that it defaults to `false`, and authentication is not loaded or applied to routes unless manually enabled in the config. So you have it turned on for your login and logout routes, but elsewhere it doesn't actually get enabled, and thus the auth parts of the request aren't available.

If I were you, I'd try adding a mode as a third argument to your `server.auth.strategy()` registration in server.js: "try" at the very least, which will cause auth to be run but doesn't actually restrict the route to only authenticated users ("required" may make more sense down the line, since I would imagine your chat application would want only authenticated users to connect).

**Comment by ghost** [comment]
Awesome, it's working now, thanks. Reply.auth is populating with values, and isAuthenticated is returning true. I added the mode "try" to server.auth.strategy, and removed "try" from the individual routes. From your suggestion, to restrict the chat page I added mode "required", and strategy "session" only to the /chat route. This makes more sense to have it run at the server level, works great.
